IBP-6079 / IBP-6080 - fix obsolete variable handling in BRAPI and PUT study
IntegratedBreedingPlatform/Middleware pull request #1402
Opened 2022-11-28 07:43 UTC by cheryleigh

2022-11-29 08:09 UTC, mderamos approved these changes

2022-12-06 06:54 UTC, abatac requested changes

2022-12-06 06:54 UTC, abatac commented on src/main/java/org/generationcp/middleware/pojos/oms/CVTerm.java
> +		return this.isObsolete != null && this.isObsolete > 0;
Is there a reason why it needs to check if isObsolete is null? I think is_obsolete table is not null and defaults to 0 value.

2022-12-06 06:54 UTC, abatac commented on src/main/java/org/generationcp/middleware/service/impl/analysis/SiteAnalysisServiceImpl.java
> +	public static final String OBSOLETE_VARIABLE_ERROR = "variableName specified marked as obsolete: ";
Externalize this error message

2022-12-09 02:53 UTC, abatac approved these changes

2022-12-09 02:53 UTC, merged