IBP-6162 enforce germplasm name type uniqueness
IntegratedBreedingPlatform/Middleware pull request #1416
Opened 2023-01-31 01:31 UTC by mderamos

2023-01-31 03:20 UTC, abatac requested changes

2023-01-31 03:20 UTC, abatac commented on src/main/resources/liquibase/crop_changelog/23_1_0.xml
> +                    INNER JOIN udflds nameType ON nameType.fldno = name.ntype
Also filter by ftype = 'NAME' to ensure only names are processed:

INNER JOIN udflds nameType ON nameType.fldno = name.ntype AND nameType.ftype = 'NAME'

2023-02-01 20:19 UTC, clarysabel commented on src/main/resources/liquibase/crop_changelog/23_1_0.xml
> +                OPEN gid_with_invalid_name_types;
@mderamos I am concerned about opening a cursor and iterating case by case, there should be way to simplify it. Not only making it more readable but improving the performance too, like creating a temporary table and identify the different scenarios. 
When writing migrations we should avois as much as possible to iterate when we can run massive update or delete sentences. 
I was doing some analysis on this first SP, I will share with you my ideas, I did not have time to test it and complete it but I want to share it and see if you went into a similar exercise. 
CC @abatac

2023-02-02 05:47 UTC, abatac commented on src/main/resources/liquibase/crop_changelog/23_1_0.xml
> +                SET n.ntype = udflds.fldno;
Add condition here: 

WHERE n.ntype <> udflds.fldno;

To make sure that only names that do not match the updated udflds.fldno will be updated.

2023-02-02 05:48 UTC, abatac commented on src/main/resources/liquibase/crop_changelog/23_1_0.xml
> +            DROP TABLE name_with_duplicates;
How's the performance of this liquibase script compared to the cursor approach?

2023-02-06 01:49 UTC, abatac approved these changes

2023-02-06 01:50 UTC, merged