IBP-3899 Refactor Sorted Page Request
IntegratedBreedingPlatform/Middleware pull request #861
Opened 2020-08-17 05:23 UTC by abatac

2020-09-08 02:27 UTC, darla-leafnode commented on src/main/java/org/generationcp/middleware/dao/dms/DmsProjectDao.java
> +	public List<StudyDto> getStudies(final StudySearchFilter studySearchFilter, final PageRequest pageRequest) {
Better use the `final Pageable pageable` in this DAO class to be consistent with other classes

2020-09-08 02:42 UTC, darla-leafnode commented on src/main/java/org/generationcp/middleware/dao/dms/ObservationUnitsSearchDao.java
> +		final String observationVariableName, final PageRequest pageRequest) {
Same here use `final Pageable pageable` to be consistent

2020-09-08 02:42 UTC, darla-leafnode commented on src/main/java/org/generationcp/middleware/service/api/dataset/DatasetService.java
> +		int studyId, int datasetId, ObservationUnitsSearchDTO searchDTO, PageRequest pageRequest);
Use final Pageable pageable to be consistent

2020-09-08 02:43 UTC, darla-leafnode commented on src/main/java/org/generationcp/middleware/service/api/study/StudyService.java
> +	List<StudyDto> getStudies(StudySearchFilter studySearchFilter, PageRequest pageRequest);
Use` final Pageable pageable`

2020-09-08 02:45 UTC, darla-leafnode commented on src/main/java/org/generationcp/middleware/service/impl/dataset/DatasetServiceImpl.java
> +		// TODO: IBP-3899
Remove TODO

2020-09-08 02:46 UTC, darla-leafnode commented on src/main/java/org/generationcp/middleware/service/impl/dataset/DatasetServiceImpl.java
> +	private void fillSearchDTO(final int studyId, final int datasetId, final ObservationUnitsSearchDTO searchDTO, final Pageable pageable) {
pageable parameter is unused in `fillSearchDTO`

2020-09-08 02:52 UTC, darla-leafnode commented on src/main/java/org/generationcp/middleware/service/impl/inventory/PlantingServiceImpl.java
> +		// TODO: IBP-3899
Why is there a TODO here still?

2020-09-08 02:53 UTC, darla-leafnode commented on src/main/java/org/generationcp/middleware/service/impl/study/StudyServiceImpl.java
> +	public List<StudyDto> getStudies(final StudySearchFilter studySearchFilter, final PageRequest pageRequest) {
Same here, use `final Pageable pageable`

2020-09-08 02:54 UTC, darla-leafnode requested changes
Hi @abatac - please address my comments

2020-09-08 03:39 UTC, abatac commented
> Hi @abatac - please address my comments

This is done.

2020-09-09 02:50 UTC, darla-leafnode approved these changes

2020-09-09 02:51 UTC, merged