IBP-4209: moved 'MG_MANAGE_INVENTORY' permission to 'MANAGE_GERMPLASM'
IntegratedBreedingPlatform/Middleware pull request #991
Opened 2021-02-23 17:15 UTC by lik-83

2021-03-01 15:39 UTC, clarysabel commented
Hi @lik-83 
The changeset seems to be fine if we want the option to still be present in Germplasm List.
Though, We need to modify the Preauthorize in BMSAPI in PermissionsEnum.HAS_CREATE_LOTS_BATCH to also consider the new tree for the permission

2021-07-14 20:15 UTC, clarysabel requested changes
Hi @cuenyad 
I left some comments in this PR

2021-07-14 21:28 UTC, cuenyad commented on src/main/java/org/generationcp/middleware/domain/inventory/common/SearchTypeComposeDto.java
> +public class SearchTypeComposeDto {
done.

2021-07-14 21:28 UTC, cuenyad commented on src/main/resources/liquibase/workbench_changelog/18_3_0.xml
> +					(name = 'MG_MANAGE_INVENTORY' AND parent_id =
done.

2021-07-14 21:28 UTC, cuenyad commented on src/main/resources/liquibase/workbench_changelog/18_3_0.xml
> +        <comment>Update MG_MANAGE_INVENTORY permission</comment>
done.

2021-07-14 21:28 UTC, cuenyad commented on src/main/java/org/generationcp/middleware/domain/inventory/common/SearchTypeComposeDto.java
> +	private String searchType;
done.

2021-07-14 21:29 UTC, cuenyad commented on src/main/java/org/generationcp/middleware/domain/inventory/common/SearchTypeComposeDto.java
> +		MANAGE_STUDY("ManageStudy"), GERMPLASM_SEARCH("GermplasmSearch");
done.

2021-07-16 21:02 UTC, merged